import Image from 'next/image';
import Link from 'next/link';
import ProjectMetadata from '@/components/ProjectMetadata';
import ProjectNavigation from '@/components/ProjectNavigation';
import BackToTop from '@/components/BackToTop';

type Figure = readonly [string, string];
const denoiserTraining: Figure[] = [
  ['part1_noising_visualization.png', 'Input digits with increasing Gaussian noise σ'], ['part1_training_loss.png', 'MSE loss over five denoiser-training epochs'], ['part1_epoch1_results.png', 'Test denoising after epoch 1'], ['part1_epoch5_results.png', 'Test denoising after epoch 5'], ['part1_ood_results.png', 'Test results across unseen noise levels'],
];
const pureNoise: Figure[] = [
  ['part1_pure_noise_loss.png', 'Loss when predicting digits from pure noise'], ['part1_pure_noise_epoch1.png', 'Pure-noise outputs after epoch 1'], ['part1_pure_noise_epoch5.png', 'Pure-noise outputs after epoch 5'],
];
const flow: Figure[] = [
  ['part2_time_training_loss.png', 'Time-conditioned flow-matching loss'], ['part2_time_samples_epoch1.png', 'Time-conditioned samples after epoch 1'], ['part2_time_samples_epoch5.png', 'Time-conditioned samples after epoch 5'], ['part2_time_samples_epoch10.png', 'Time-conditioned samples after epoch 10'], ['part2_class_training_loss.png', 'Class-conditioned flow-matching loss'], ['part2_class_samples_epoch1.png', 'Class-conditioned samples after epoch 1'], ['part2_class_samples_epoch5.png', 'Class-conditioned samples after epoch 5'], ['part2_class_samples_epoch10.png', 'Class-conditioned samples after epoch 10'],
];
function Gallery({ items }: { items: Figure[] }) { return <div className="grid grid-cols-1 md:grid-cols-3 gap-5">{items.map(([file, caption]) => <figure key={file}><div className="relative aspect-square bg-gray-100"><Image src={`/flow-matching/${file}`} alt={caption} fill sizes="(max-width:768px) 100vw, 33vw" className="object-contain" /></div><figcaption className="mt-2 text-xs text-gray-500">{caption}</figcaption></figure>)}</div>; }
const Code = ({ children }: { children: React.ReactNode }) => <code className="rounded bg-gray-100 px-1.5 py-0.5 text-[.9em] text-gray-800">{children}</code>;
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="bg-white p-8 mb-8"><h2 className="text-xl font-semibold text-gray-900 mb-4">{title}</h2>{children}</section>; }
function Copy({ children }: { children: React.ReactNode }) { return <div className="space-y-4 leading-relaxed text-gray-600">{children}</div>; }

export default function FlowMatchingPage() { return <div className="project-page min-h-screen bg-white"><div className="max-w-6xl mx-auto px-6 py-12">
  <Link href="/" className="inline-flex items-center text-gray-600 hover:text-gray-900 mb-8 transition-colors"><svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg>Back to Projects</Link>
  <div className="bg-white p-8 mb-8"><h1 className="text-4xl font-bold text-gray-900 mb-4">Flow Matching from Scratch</h1><div className="w-full h-px bg-gray-300 mb-8" /><ProjectMetadata myRole="Developer" year="2026" contribution="Generative Modeling, UNet Implementation, Training" tools="Python, PyTorch, torchvision" team="Individual project" /></div>
  <Section title="Overview"><Copy><p>Built and trained a flow-matching model on MNIST from scratch. The project begins with a single-step UNet denoiser, then adds time conditioning for iterative generation and class conditioning for controllable digit synthesis.</p><p>The model architecture, training setup, and all results below follow the original technical report.</p></Copy></Section>
  <Section title="Single-Step Denoising UNet"><Copy><p>I implemented the prescribed UNet as a contracting encoder and expanding decoder connected with skip connections. Conv layers use 3×3 kernels; stride-2 downsampling maps 28×28 MNIST images to a 7×7 bottleneck; transposed convolutions restore spatial resolution.</p><p>The unconditional model uses hidden dimension 128 and is trained with Adam (lr 1e-4), MSE loss, batch size 256, σ=0.5 input noise, and five epochs. It recovers digits well at the trained noise level. At σ=0.8 and 1.0, outputs degrade because the model was never trained for those distributions.</p></Copy><h3 className="text-lg font-medium text-gray-900 mt-8 mb-2">Training-distribution denoising</h3><p className="text-sm leading-relaxed text-gray-600 mb-4">These figures move from the injected noise, to loss over training, to test reconstructions and robustness outside σ=0.5.</p><Gallery items={denoiserTraining} /><h3 className="text-lg font-medium text-gray-900 mt-8 mb-2">Pure-noise failure case</h3><p className="text-sm leading-relaxed text-gray-600 mb-4">Because pure noise contains no digit identity, MSE collapses toward an average-looking digit rather than a specific class.</p><Gallery items={pureNoise} /></Section>
  <Section title="Time-Conditioned Flow Matching"><Copy><p>FCBlocks map scalar t to channel-wise signals at two decoder locations: after unflattening and after the first UpBlock. The model is trained on random timesteps with <Code>x_t = (1−t)x₀ + tx₁</Code>, predicting velocity <Code>x₁ − x₀</Code>.</p><p>The first tile is the training-loss curve; the next three are samples generated from pure noise after epochs 1, 5, and 10. The time-conditioned UNet uses hidden dimension 64, batch size 64, an initial 1e-2 learning rate with exponential decay, and 50 Euler steps at inference. Samples become legible by epoch 10, though they remain softer than class-conditioned outputs.</p></Copy><div className="mt-8"><Gallery items={flow.slice(0, 4)} /></div></Section>
  <Section title="Class-Conditioned Generation"><Copy><p>Two further FCBlocks consume one-hot class labels and combine their output with time conditioning at the same decoder stages. With <Code>p_uncond=0.1</Code>, labels are dropped during training so the model learns both conditional and unconditional predictions.</p><p>The first tile is the class-conditioned loss curve. The next three grids show four samples for every digit class after epochs 1, 5, and 10. During sampling, classifier-free guidance with γ=5 combines conditional and unconditional flows: <Code>u = u_uncond + γ(u_cond − u_uncond)</Code>. By epoch 10, each row consistently corresponds to its target digit and is sharper than time-only generation.</p></Copy><div className="mt-8"><Gallery items={flow.slice(4)} /></div></Section>
</div><ProjectNavigation currentProjectId="flow-matching" /><BackToTop /></div>; }
