import Image from 'next/image';
import Link from 'next/link';
import ProjectMetadata from '@/components/ProjectMetadata';
import ProjectNavigation from '@/components/ProjectNavigation';
import BackToTop from '@/components/BackToTop';

const groups = [
  ['Input & SIFT features', [['step0_original_images.png', 'Input living-room image pair'], ['step2_sift_keypoints.png', 'SIFT keypoints']]],
  ['Correspondence matching', [['step3_correspondences_before_ransac.png', 'Correspondences before RANSAC'], ['step3_feature_matching_nndr_histogram.png', 'NNDR distribution'], ['step3_feature_matching_top5_nndr.png', 'Top NNDR matches'], ['step3_feature_matching.png', 'Feature matches']]],
  ['Robust pose estimation', [['step4_correspondences_after_ransac.png', 'RANSAC inlier correspondences'], ['step4_epipolar_lines.png', 'Epipolar lines'], ['step4_feature_matching_after_ransac.png', 'Matches after RANSAC'], ['step4_ransac_convergence.png', 'RANSAC convergence']]],
  ['Sparse reconstruction', [['step5_3d_reconstruction.png', 'Triangulated 3D point cloud'], ['step5_camera_poses.png', 'Recovered camera poses'], ['step5_pipeline_grid.png', 'Pipeline summary'], ['step5_pose_summary.png', 'Pose summary'], ['step5_v1.png', 'Viser view 1'], ['step5_v2.png', 'Viser view 2'], ['step5_v3.png', 'Viser view 3']]],
] as const;

function Gallery({ images }: { images: readonly (readonly [string, string])[] }) {
  return <div className="grid grid-cols-1 md:grid-cols-2 gap-5">{images.map(([file, alt]) => <figure key={file}><div className="relative aspect-[1.55] bg-gray-100"><Image src={`/structure-from-motion/${file}`} alt={alt} fill sizes="(max-width:768px) 100vw, 50vw" className="object-contain" /></div><figcaption className="mt-2 text-xs text-gray-500">{alt}</figcaption></figure>)}</div>;
}
const Code = ({ children }: { children: React.ReactNode }) => <code className="rounded bg-gray-100 px-1.5 py-0.5 text-[.9em] text-gray-800">{children}</code>;

export default function StructureFromMotionPage() {
  return <div className="project-page min-h-screen bg-white"><div className="max-w-6xl mx-auto px-6 py-12">
    <Link href="/" className="inline-flex items-center text-gray-600 hover:text-gray-900 mb-8 transition-colors"><svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg>Back to Projects</Link>
    <div className="bg-white p-8 mb-8"><h1 className="text-4xl font-bold text-gray-900 mb-4">Simple Structure from Motion</h1><div className="w-full h-px bg-gray-300 mb-8" /><ProjectMetadata myRole="Developer" year="2026" contribution="Computer Vision, Geometry, 3D Reconstruction" tools="Python, NumPy, OpenCV, SciPy, Viser" team="Individual project" /></div>
    <section className="bg-white p-8 mb-8"><h2 className="text-xl font-semibold text-gray-900 mb-4">Overview</h2><div className="space-y-4 leading-relaxed text-gray-600"><p>Built a sparse Structure from Motion pipeline that estimates image correspondences, camera motion, and 3D scene points from two staff-provided iPhone 15 Pro living-room images.</p><p>Settings: random seed 42; 8,000 maximum SIFT features; NNDR threshold 0.8; 2,000 RANSAC iterations; and a Sampson-distance inlier threshold of 0.001.</p></div></section>
    <section className="bg-white p-8 mb-8"><h2 className="text-xl font-semibold text-gray-900 mb-4">Camera Intrinsics &amp; Features</h2><div className="space-y-4 leading-relaxed text-gray-600"><p>Computed the intrinsic matrix from a 6.765 mm focal length, 9.757 mm sensor width, and 1280×960 image dimensions: <Code>f = 6.765 × (1280 / 9.757) ≈ 887.49 px</Code>, with principal point (640, 480). The height calculation produced 887.46 px, supporting the square-pixel assumption.</p><p>Used OpenCV SIFT because it is robust to the pair&apos;s rotation and translation. The detector produced 7,807 features in image one and 7,372 in image two, using default SIFT parameters except an 8,000 feature cap.</p></div><div className="mt-8"><Gallery images={groups[0][1]} /></div></section>
    <section className="bg-white p-8 mb-8"><h2 className="text-xl font-semibold text-gray-900 mb-4">Matching &amp; Robust Pose Recovery</h2><div className="space-y-4 leading-relaxed text-gray-600"><p>OpenCV&apos;s BFMatcher compares SIFT descriptors with L2 distance. An NNDR threshold of 0.8 retained 617 candidate correspondence pairs; it is intentionally permissive because geometry-based RANSAC removes outliers downstream.</p><p>Each RANSAC iteration samples eight correspondences, estimates an Essential matrix with the 8-point algorithm, decomposes it into four candidate poses, and uses a cheirality check to select the pose with the most positive-depth triangulations. All correspondences are scored with Sampson distance, then the best model is refined using every inlier.</p><p>The final model retained 469/617 inliers (76.01%). Tightening epsilon from 0.01 to 0.001 corrected an initially incorrect pose by excluding geometrically inconsistent matches.</p></div><div className="mt-8"><Gallery images={groups[1][1]} /></div><div className="mt-8"><Gallery images={groups[2][1]} /></div></section>
    <section className="bg-white p-8 mb-8"><h2 className="text-xl font-semibold text-gray-900 mb-4">Triangulation &amp; Point Cloud</h2><div className="space-y-4 leading-relaxed text-gray-600"><p>Inlier pairs are triangulated with Direct Linear Transform, then filtered by positive depth and reprojection error. The final sparse reconstruction contains 469 points, with mean depth 1.6068 and depth range [0.5960, 20.5436].</p><p>The recovered rotation has Euler angles roll 21.36°, pitch 22.08°, yaw 12.40°; the normalized translation is [-0.73835, 0.55234, 0.38698]. The final point cloud can be explored through the generated Viser scene data.</p></div><div className="mt-8"><Gallery images={groups[3][1]} /></div></section>
  </div><ProjectNavigation currentProjectId="structure-from-motion" /><BackToTop /></div>;
}
