import Image from 'next/image';
import Link from 'next/link';
import ProjectMetadata from '@/components/ProjectMetadata';
import ProjectNavigation from '@/components/ProjectNavigation';
import BackToTop from '@/components/BackToTop';

type Figure = readonly [string, string];
const range = (prefix: string, values: number[], label: string): Figure[] => values.map((value) => [`${prefix}${value}.png`, `${label} · i_start=${value}`]);
const campanileEdit = range('campanile_sdedit_', [1, 3, 5, 7, 10, 20], 'Campanile SDEdit');
const webEdit: Figure[] = [['web_image_original.png', 'Web-image input'], ...range('web_sdedit_', [1, 3, 5, 7, 10, 20], 'Web-image SDEdit')];
const drawingOne: Figure[] = [['drawn1_original.png', 'Hand-drawn image 1 input'], ...range('drawn1_sdedit_', [1, 3, 5, 7, 10, 20], 'Hand-drawn image 1 SDEdit')];
const drawingTwo: Figure[] = [['drawn2_original.png', 'Hand-drawn image 2 input'], ...range('drawn2_sdedit_', [1, 3, 5, 7, 10, 20], 'Hand-drawn image 2 SDEdit')];
const inpainting: Figure[] = [['campanile_original.png', 'Campanile original'], ['campanile_mask.png', 'Campanile mask'], ['campanile_inpainted.png', 'Campanile inpainted'], ['own_image1_original.png', 'Custom image 1 original'], ['own_image1_mask.png', 'Custom image 1 mask'], ['own_image1_inpainted.png', 'Custom image 1 inpainted'], ['own_image2_original.png', 'Custom image 2 original'], ['own_image2_mask.png', 'Custom image 2 mask'], ['own_image2_inpainted.png', 'Custom image 2 inpainted']];
const textCampanile = range('campanile_textcond_', [1, 3, 5, 7, 10, 20], 'Campanile text-conditioned edit');
const textOne = range('own1_textcond_', [1, 3, 5, 7, 10, 20], 'Custom image 1 text-conditioned edit');
const textTwo = range('own2_textcond_', [1, 3, 5, 7, 10, 20], 'Custom image 2 text-conditioned edit');
const anagrams: Figure[] = [['anagram1_normal.png', 'Lake / roses anagram · normal view'], ['anagram1_flipped.png', 'Lake / roses anagram · flipped view'], ['anagram2_normal.png', 'Flamingos / Colosseum anagram · normal view'], ['anagram2_flipped.png', 'Flamingos / Colosseum anagram · flipped view']];
const hybrids: Figure[] = [['hybrid1.png', 'Roses / Colosseum hybrid'], ['hybrid2.png', 'Plane-race hybrid']];
function Gallery({ items, cols = 'md:grid-cols-3' }: { items: Figure[]; cols?: string }) { return <div className={`grid grid-cols-1 ${cols} gap-5`}>{items.map(([file, caption]) => <figure key={file}><div className="relative aspect-square bg-gray-100"><Image src={`/diffusion-flow-matching/${file}`} alt={caption} fill sizes="(max-width:768px) 100vw, 33vw" className="object-contain" /></div><figcaption className="mt-2 text-xs text-gray-500">{caption}</figcaption></figure>)}</div>; }
const Code = ({ children }: { children: React.ReactNode }) => <code className="rounded bg-gray-100 px-1.5 py-0.5 text-[.9em] text-gray-800">{children}</code>;
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="bg-white p-8 mb-8"><h2 className="text-xl font-semibold text-gray-900 mb-4">{title}</h2>{children}</section>; }
function Copy({ children }: { children: React.ReactNode }) { return <div className="space-y-4 leading-relaxed text-gray-600">{children}</div>; }

export default function DiffusionImageEditingPage() { return <div className="project-page min-h-screen bg-white"><div className="max-w-6xl mx-auto px-6 py-12">
  <Link href="/" className="inline-flex items-center text-gray-600 hover:text-gray-900 mb-8 transition-colors"><svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg>Back to Projects</Link>
  <div className="bg-white p-8 mb-8"><h1 className="text-4xl font-bold text-gray-900 mb-4">Diffusion Image Editing</h1><div className="w-full h-px bg-gray-300 mb-8" /><ProjectMetadata myRole="Developer" year="2026" contribution="Generative Modeling, Image Editing, Experimentation" tools="Python, PyTorch, DeepFloyd IF, Diffusers" team="Individual project" /></div>
  <Section title="Overview"><Copy><p>Built a set of image-editing workflows on DeepFloyd IF: SDEdit translation, mask-based inpainting, text-conditioned image editing, visual anagrams, and hybrid images.</p><p>The methods and experiment outcomes below preserve the original report.</p></Copy></Section>
  <Section title="SDEdit Image-to-Image Translation"><Copy><p>SDEdit adds noise to an input image before denoising it. The <Code>i_start</Code> value determines the editing-versus-preservation tradeoff: lower values let the diffusion prior change the source more substantially, while higher values retain more of its original structure.</p><p>Within every sweep, read left to right as <Code>i_start</Code> = 1, 3, 5, 7, 10, and 20. The Campanile series shows the basic control. The web image and hand drawings show how non-photorealistic inputs are projected toward the model&apos;s natural-image manifold—dramatic at lower values and more source-faithful at higher values.</p></Copy><h3 className="text-lg font-medium text-gray-900 mt-8 mb-2">Photograph: Campanile</h3><p className="text-sm leading-relaxed text-gray-600 mb-4">Six edits of the same photograph at progressively larger noise-start positions.</p><Gallery items={campanileEdit} /><h3 className="text-lg font-medium text-gray-900 mt-8 mb-2">Web image</h3><p className="text-sm leading-relaxed text-gray-600 mb-4">The first tile is the input; the remaining tiles are its six SDEdit outcomes.</p><Gallery items={webEdit} cols="md:grid-cols-4" /><h3 className="text-lg font-medium text-gray-900 mt-8 mb-2">Hand-drawn image 1</h3><p className="text-sm leading-relaxed text-gray-600 mb-4">Input drawing followed by the same six-step edit sweep.</p><Gallery items={drawingOne} cols="md:grid-cols-4" /><h3 className="text-lg font-medium text-gray-900 mt-8 mb-2">Hand-drawn image 2</h3><p className="text-sm leading-relaxed text-gray-600 mb-4">A second drawing tests whether the behavior generalizes to a different sketch.</p><Gallery items={drawingTwo} cols="md:grid-cols-4" /></Section>
  <Section title="Mask-Based Inpainting"><Copy><p>At each denoising step, pixels outside the mask are reset to the original image, leaving the diffusion model free to generate only the unknown region. The resulting content is constrained by both the surrounding image and the learned image prior. Each sequence is original image, mask, then inpainted result.</p></Copy><div className="mt-8"><Gallery items={inpainting} /></div></Section>
  <Section title="Text-Conditional Editing"><Copy><p>Text prompts guide SDEdit toward a new semantic target while <Code>i_start</Code> still controls structural preservation. The experiments use prompts such as “a drawing of a group of flamingos” and “a painting of the Colosseum.” Low values are dominated by the prompt; high values maintain more of the original image&apos;s structure.</p><p>Each six-image set is ordered left to right by <Code>i_start</Code> = 1, 3, 5, 7, 10, and 20, so the transition from prompt-driven to input-driven imagery is visible within a row.</p></Copy><h3 className="text-lg font-medium text-gray-900 mt-8 mb-4">Campanile source</h3><Gallery items={textCampanile} /><h3 className="text-lg font-medium text-gray-900 mt-8 mb-4">Custom image 1 source</h3><Gallery items={textOne} /><h3 className="text-lg font-medium text-gray-900 mt-8 mb-4">Custom image 2 source</h3><Gallery items={textTwo} /></Section>
  <Section title="Visual Anagrams &amp; Hybrid Images"><Copy><p>For visual anagrams, the UNet runs once on the normal image with one prompt and once on a vertically flipped image with a second prompt. The second noise estimate is flipped back and averaged with the first, allowing the image to resolve differently when rotated.</p><p>For hybrid images, two prompt-conditioned estimates are separated by frequency using Gaussian blur (kernel 33, σ=2). Low frequencies come from one prompt and high frequencies from the other, combining different identities across viewing scales.</p></Copy><h3 className="text-lg font-medium text-gray-900 mt-8 mb-4">Visual anagrams</h3><Gallery items={anagrams} cols="md:grid-cols-2" /><h3 className="text-lg font-medium text-gray-900 mt-8 mb-4">Hybrid images</h3><Gallery items={hybrids} cols="md:grid-cols-2" /></Section>
</div><ProjectNavigation currentProjectId="diffusion-image-editing" /><BackToTop /></div>; }
