import Image from 'next/image';
import Link from 'next/link';
import ProjectMetadata from '@/components/ProjectMetadata';
import ProjectNavigation from '@/components/ProjectNavigation';
import BackToTop from '@/components/BackToTop';

const groups = [
  ['2D neural field', [['sample1.jpg', 'Training image one'], ['sample2.jpg', 'Training image two'], ['progression.png', 'Training progression: sample one'], ['PSNR.png', 'PSNR: sample one'], ['progression2.png', 'Training progression: sample two'], ['PSNR2.png', 'PSNR: sample two'], ['hyperparam_grid.png', 'Hyperparameter grid: sample one'], ['hyperparam_grid2.png', 'Hyperparameter grid: sample two']]],
  ['Multi-view NeRF', [['v.png', 'Ray sampling visualization'], ['part2_validation.png', 'Validation render'], ['part2_nerf_progression.png', 'NeRF training progression'], ['part2_lego_spherical.gif', 'Spherical novel-view render']]],
] as const;
function Gallery({ images }: { images: readonly (readonly [string, string])[] }) { return <div className="grid grid-cols-1 md:grid-cols-2 gap-5">{images.map(([file, alt]) => <figure key={file}><div className="relative aspect-[1.55] bg-gray-100"><Image src={`/neural-radiance-fields/${file}`} alt={alt} fill unoptimized={file.endsWith('.gif')} sizes="(max-width:768px) 100vw, 50vw" className="object-contain" /></div><figcaption className="mt-2 text-xs text-gray-500">{alt}</figcaption></figure>)}</div>; }
const Code = ({ children }: { children: React.ReactNode }) => <code className="rounded bg-gray-100 px-1.5 py-0.5 text-[.9em] text-gray-800">{children}</code>;

export default function NeuralRadianceFieldsPage() { return <div className="project-page min-h-screen bg-white"><div className="max-w-6xl mx-auto px-6 py-12">
  <Link href="/" className="inline-flex items-center text-gray-600 hover:text-gray-900 mb-8 transition-colors"><svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg>Back to Projects</Link>
  <div className="bg-white p-8 mb-8"><h1 className="text-4xl font-bold text-gray-900 mb-4">Neural Radiance Fields</h1><div className="w-full h-px bg-gray-300 mb-8" /><ProjectMetadata myRole="Developer" year="2026" contribution="Neural Rendering, Model Implementation, Training" tools="Python, PyTorch, NumPy, Matplotlib, Viser" team="Individual project" /></div>
  <section className="bg-white p-8 mb-8"><h2 className="text-xl font-semibold text-gray-900 mb-4">Overview</h2><div className="space-y-4 leading-relaxed text-gray-600"><p>Implemented neural fields in two settings: mapping 2D pixel coordinates to image color, then learning a Neural Radiance Field (NeRF) for novel-view synthesis of a multi-view Lego scene reconstructed by COLMAP.</p><p>Implementation choices and results are documented below.</p></div></section>
  <section className="bg-white p-8 mb-8"><h2 className="text-xl font-semibold text-gray-900 mb-4">Part 1: Fit a 2D Neural Field</h2><div className="space-y-4 leading-relaxed text-gray-600"><p>A sinusoidal positional encoder transforms a pixel coordinate (u, v) into 42 dimensions using the original coordinates plus sine/cosine terms through L=10. A four-layer width-256 MLP with ReLU activations maps the encoding to RGB through a Sigmoid output.</p><p>At each iteration, 10,000 normalized pixel coordinates and colors are sampled. Adam (lr 1e-2) and MSE loss train the model for 3,000 iterations. Reconstructions become recognizable around iteration 300, resolve finer details by 1,000, and reach approximately 27 dB PSNR by 3,000.</p><p>A 2×2 sweep showed that L=1 produces only low-frequency blurry results regardless of width; L=10 with width 16 lacks capacity and artifacts remain; L=10 with width 256 captures the sharpest high-frequency detail.</p></div><div className="mt-8"><Gallery images={groups[0][1]} /></div></section>
  <section className="bg-white p-8 mb-8"><h2 className="text-xl font-semibold text-gray-900 mb-4">Part 2: Multi-View Neural Radiance Field</h2><div className="space-y-4 leading-relaxed text-gray-600"><p>Using 100 training images, pixel centers are converted to rays with camera intrinsics K and camera-to-world matrices. Rays use a 0.5 coordinate offset, and are sampled between near=2.0 and far=6.0. Training perturbs samples within each interval, while inference uses fixed positions for consistent rendering.</p><p><Code>RaysData</Code> precomputes all origins, directions, and RGB targets. The NeRF encodes 3D positions with L=10 (63 dimensions) and view directions with L=4 (27 dimensions), then uses two four-layer width-256 ReLU blocks with a position skip connection. Separate density (ReLU) and color (Sigmoid) heads predict per-sample radiance and density.</p><p>Volume rendering composites colors with transmittance-weighted accumulation. Adam (lr 5e-4), MSE, 10,000 rays/iteration, and 32 samples/ray trained for 5,000 iterations. PSNR rose from roughly 11 dB to ~21 dB near iteration 700 and finished around 24.8 dB, above the 23 dB target.</p></div><div className="mt-8"><Gallery images={groups[1][1]} /></div></section>
</div><ProjectNavigation currentProjectId="neural-radiance-fields" /><BackToTop /></div>; }
